[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "cd callcrew-backend && npm ci",
  "cd ../callcrew-dashboard && npm ci && npm run build"
]

[start]
cmd = "cd callcrew-backend && node server.js"
